// <auto-generated />
using System;
using Jogo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jogo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240327181732_UpdDates")]
    partial class UpdDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Jogo.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdCategoriaPai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriaPai");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Jogo.Domain.Entities.Prato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Prato");
                });

            modelBuilder.Entity("Jogo.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("Jogo.Domain.Entities.Categoria", "CategoriaPai")
                        .WithMany("SubCategorias")
                        .HasForeignKey("IdCategoriaPai")
                        .HasConstraintName("FK_SubCategoria_CategoriaPai");

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("Jogo.Domain.Entities.Prato", b =>
                {
                    b.HasOne("Jogo.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Pratos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Prato_Categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Jogo.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Pratos");

                    b.Navigation("SubCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
